# Tensors 1
#### Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, tensors are used to encode the input and output of a model, aswell as the model's parameters.
#### They are similar to NumPy ndarrays. except that tensors can run on GPU and other hardware accelerators. also share same underlying memory with NumPy arrays, eliminating data copying(bridges with Numpy).
### Tensors are optimized for automatic differentiation(autograd)


In [1]:
import torch
import numpy as np

C:\Users\Fatihi\.conda\envs\Pytorch_1\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [7]:
#Initializing a Tensor

#Initializing directly from data
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

#From a Numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

#From another tensor
x_ones = torch.ones_like(x_data)#retain the properties of x_data
print(f'Ones Tensor: \n {x_ones} \n')
x_rand = torch.rand_like(x_data, dtype = torch.float) #overrides datatype of x_data
print(f'Random Tensor: \n {x_rand} \n')

#With random or constant values:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f'Random Tensors: \n {rand_tensor} \nOnes Tensor: \n {ones_tensor} \nZeros Tensor: \n {zeros_tensor} \n')


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8098, 0.3596],
        [0.6337, 0.9740]]) 

Random Tensors: 
 tensor([[0.3871, 0.7619, 0.9531],
        [0.7892, 0.8326, 0.4166]]) 
Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 
Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



# Attributes of a Tensor
### Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [8]:
tensor = torch.rand(3,4)
print(f'Shape of tensor: {tensor.shape}')
print(f'Datatype of tensor: {tensor.dtype}')
print(f'Device tensor is stored on: {tensor.device}')

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Operations on Tensors
### There are over 100 tensor operations including arithmetics, linear algebra, matrix manipulation(transposing, indexing, slicing), sampling... [check link](https://pytorch.org/docs/stable/torch.html) for more about tensor operations.
### tensor are created on cpu, explicitly move tensors to the GPU using .to method(large tensors copying can be expensive in terms of time/memory)

In [11]:
#moving our tensor to GPU
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [14]:
#Standard numpy-like indexing and slicing
tensor = torch.ones(4,4)
print(f'First Row: {tensor[0]} \n First Col: {tensor[:,0]} \n Last Col: {tensor[...,-1]}')
tensor[:,1] =0
print(tensor)
#Joining tensors
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)


First Row: tensor([1., 1., 1., 1.]) 
 First Col: tensor([1., 1., 1., 1.]) 
 Last Col: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [24]:
# @Arithmetic Operations
#This compute the matrix multiplication between two tensors. y1, y2, y3 will have the same values
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)



tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [25]:
#This compute the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [26]:
# @Single-element tensors if you have one-element tensor, for ex by aggregating all values of a tensor into one value
# you can convert it to python numerical value using item()
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item), agg, type(agg))

12.0 <class 'float'> tensor(12.) <class 'torch.Tensor'>


In [27]:
# @In-place operations that store the result into the operand and called inplace.
# They are denoted by a _ suffix. for ex: x.copy_(y), x.t_(), will change x
print(tensor, '\n')
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [29]:
# Bridge with numpy given both share same underlying memory locations. and changing one will change the other
t = torch.ones(5)
print(f'Before\nt: {t}')
n = t.numpy()
print(f"n:{n}")

t.add_(1)
print(f'After\nt: {t}')
print(f"n:{n}")

Before
t: tensor([1., 1., 1., 1., 1.])
n:[1. 1. 1. 1. 1.]
After
t: tensor([2., 2., 2., 2., 2.])
n:[2. 2. 2. 2. 2.]


In [30]:
#Numpy array to Tensor
n = np.ones(4)
t = torch.from_numpy(n)

np.add(n,1, out=n)

print(f"t:{t}")
print(f"n:{n}")

t:tensor([2., 2., 2., 2.], dtype=torch.float64)
n:[2. 2. 2. 2.]
